CREATE TABLE SAMPLE_TEMP  (
	STID BIGINT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CODE VARCHAR(100) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	TARGET_DATE CHAR(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE SAMPLE  (
	SID BIGINT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CODE VARCHAR(100) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	TARGET_DATE CHAR(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;